### ISSUE TITLE
Implement a back-end using FastAPI

### ISSUE THREAD

**Issue by sglavoie** [sglavoie/uol-grades-calculator-server#1]
## Acceptance

* [x] A FastAPI back-end communicates with the `ugc` Python package to retrieve and display relevant grades data.
* [x] Basic API endpoints have been implemented to **retrieve** data generated by `ugc` (no writing to the file system yet).

## Tasks

* [x] Create an empty project following along with https://fastapi.tiangolo.com/tutorial/
* [x] Import the latest version of `ugc` into this project as a requirement.
* [x] Implement basic `GET` endpoints:
  * [x] `/check/score-accuracy`
  * [x] `/summarize/all`
  * [x] `/summarize/done`
  * [x] `/summarize/progress`
* ~Use Pydantic models.~ Sending back very simple JSON responses and providing no support for query parameters → not needed for now.

## Analysis

See https://github.com/sglavoie/uol-grades-calculator/issues/22 for the original need for this back-end.

![image](https://user-images.githubusercontent.com/32682903/130367355-ed0f5011-e51e-406d-b0f2-452694b4b01d.png)

```plantuml
@startuml
package "Front-end" {
  [React]
}

package "Back-end" {
  API - [FastAPI]
  package "CLI" {
    [ugc]
    database "Database" {
      [File system]
    }
  }
}

[React] ..> [FastAPI]
[FastAPI] ..> [ugc]
[ugc] -right-- [File system]

note as R
  Only interfaces with the API
  provided by FastAPI
end note

React -right-- R

note right of FastAPI
  Provides an API to the
  front-end, which
  endpoints call the
  `ugc` Python package
end note

note as U
  Stand-alone application
  performing file system
  operations to work
  with the Grades data
end note

ugc -left-- U

note bottom of [File system]
  Currently, the CLI reads data from JSON and YML files, but this
  behavior is isolated from the rest of the back-end and can be
  upgraded later to use a more robust system if needed
end note
@enduml
```

**Comment by sglavoie** [comment]
FIXED: All tasks were done and changes were merged into `main` in 9fa5c7861155fdc9975fdb2b0c536cff06d0155b.
