### ISSUE TITLE
Front-end: `PlotModules` component should allow users to request a customized plot

### ISSUE THREAD

**Issue by sglavoie** [sglavoie/uol-grades-calculator-server#10]
## Acceptance

* [ ] Users can set options in the UI to generate the output of a custom plot.
* [ ] Users can click on a `Download plot` button to download a PNG image of the output.

## Tasks

* [ ] Implement all options from the back-end that leverage existing functionality (ref: #9).
  * [ ] Implement an input field to set the `title` of the plot.
    * [ ] If the field is left empty, do not send the `title` option to the back-end.
    * [ ] If `title` contains a value, disable `title_no_date` and enable `title_keep_date`.
    * [ ] If `title` goes from having a value to not having a value, enable `title_no_date` and disable `title_keep_date`.
  * [x] Implement a numeric input field to set the `dpi` option.
    * [x] Field is limited within the range `100` to `600` (this is what the back-end accepts).
  * [ ] Implement checkboxes to toggle the following options:
    * [ ] `no_module_names` and `long_module_names`
      * [ ] When `no_module_names` is **checked**, disable `long_module_names` and send only the option `no_module_names` set to `true`.
      * [ ] When `no_module_names` is **unchecked**, enable `long_module_names` and send only the option `long_module_names`.
    * [x] `no_avg_overall`
    * [x] `no_avg_unweighted`
    * [x] `no_avg_weighted`
    * [ ] `no_avgs`
      * [ ] When this option is ticked, disable the other ones (`no_avg_overall`, `no_avg_unweighted` and `no_avg_weighted`).
    * [x] `no_grades`
    * [x] `no_trend`
    * [x] `title_keep_date`
    * [x] `title_no_date`
* [ ] Implement a download button (`Download plot`) for the output plot.

## Analysis

As part of this issue, existing functionality in the back-end should be added to the UI. Since the flow is different from the CLI, the `--path TEXT` option does not have any equivalent while the `--filename TEXT` can be tackled in a separate issue when adding the ability to download the plot via the click of a button.

### Before generating graph

![Plot modules - NO graph](https://user-images.githubusercontent.com/32682903/139565477-8b9d84ac-4d1d-4ef4-ad4a-29dcf11fa4a7.png)

### After generating graph

![Plot modules - graph](https://user-images.githubusercontent.com/32682903/139565495-9f7338e6-ab29-4509-9550-98b71baa42a2.png)
