### ISSUE TITLE
Implement a front-end with React

### ISSUE THREAD

**Issue by sglavoie** [sglavoie/uol-grades-calculator-server#2]
## Acceptance

* [x] A React front-end is set up to call the FastAPI back-end from #1.
* [x] Basic endpoints that are available in the back-end are called from the front-end and the data is displayed in a basic way.

## Tasks

* [x] Set up a basic project using https://github.com/facebook/create-react-app.
* [x] Use TypeScript to properly document types. Read:
  * [x] https://create-react-app.dev/docs/adding-typescript/
  * [x] https://reactjs.org/docs/static-type-checking.html#typescript
  * [x] https://ts.chibicode.com/todo/
  * [x] https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes.html
  * [x] https://react-typescript-cheatsheet.netlify.app/docs/basic/setup (±)
* Set up basic components to display data in the home page:
  * [x] Display data from `/check/score-accuracy`
  * [x] Display data from `/summarize/done`
  * [x] Display data from `/summarize/all`
  * [x] Display data from `/summarize/progress`
* [x] Set up basic 404 not found component for non-existent routes.
* [x] Refactor endpoints to avoid repeating the same calls to the back-end in the hooks, which are mostly the same.

## Analysis

See https://github.com/sglavoie/uol-grades-calculator/issues/22 for the original need for this front-end.
