### ISSUE TITLE
Update `/generate-sample` endpoint to send back `grades-template.json` and download it from the front-end

### ISSUE THREAD

**Issue by sglavoie** [sglavoie/uol-grades-calculator-server#3]
## Acceptance

* [x] FastAPI returns a `FileResponse` when going to `/generate-sample`.
* [x] The front-end downloads the file to the user's computer.

## Tasks

Back-end:
* [x] Modify API endpoint for `/generate-sample` to return the appropriate response.

Front-end:
* [x] Fetch the sample file by calling the back-end.
* [x] Add a link in the front-end to download the sample file.

## Analysis

See https://fastapi.tiangolo.com/advanced/custom-response/#fileresponse
