### ISSUE TITLE
Allow users to upload their own grades file and remove local storage data as desired

### ISSUE THREAD

**Issue by sglavoie** [sglavoie/uol-grades-calculator-server#4]
## Acceptance

* [x] Users are first presented a screen to upload their grades config file if no data is found in the localStorage.
* [x] Users can access and use the existing "features" of the UI once their grades are loaded.
* [x] Users can remove all the local data by clicking on a link.
* [x] Users can upload new grades to overwrite existing data, being asked to confirmed before proceeding.

## Tasks

* [x] Implement a global state manager with Redux.
* [x] If no data is found in localStorage, display only a component to upload existing grades when loading the home page and prevent access to the other routes.
* [x] Add an `Upload existing grades` link to upload a file and cache the grades.
* [x] Validate grades file with `ugc` once uploaded before caching any data.
* [x] Add a `Clear grades data` link to remove all data from localStorage.
* [x] Check whether grades are already loaded before uploading a new file and ask the user whether they'd want to overwrite their existing grades.

## Analysis

* As it stands, the server is only useful if installed locally and launched with the ability to fetch an existing grades file. There is no reloading on the fly of new data nor is there the possibility to deploy somewhere else and be able to easily read existing grades without the grades file being present on the server.
* Using [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) would be convenient to keep data intact on the website until the user cache is cleared.
* Having the ability to upload an existing config file is necessary since there's no way to build the config file from scratch from the UI at this moment.

**Comment by sglavoie** [comment]
FIXED: Done in f61dcce0c1e1d83a02393a94c85a71eac53d7c09.
