### ISSUE TITLE
Command `generate-sample` should allow users to start tracking their grades from scratch

### ISSUE THREAD

**Issue by sglavoie** [sglavoie/uol-grades-calculator-server#5]
## Acceptance

* [x] There is a link to generate a config file from scratch. If grades are already loaded in the UI, users are asked whether they would like to delete their existing grades.

## Tasks

* [x] Add a link to generate a new, empty config file (call `ugc generate-sample` in the background to get a valid file).
* [x] Store JSON config file to localStorage.
* [x] Check for the existence of grades and offer to overwrite them.

## Analysis

* Starting from scratch is likely to be the most common scenario (if the app is used by anyone at all some day). It would leverage the existing `ugc generate-sample` command in the back-end to create a valid file and its "overwrite variant" (i.e. `ugc generate-sample -f`) would just clear the cache and store the new empty config, which would be dealt with by the front-end.
* Using YAML and having to convert between file formats is not convenient: `ugc` should use JSON by default.
