### ISSUE TITLE
Show a plot of the progress made in the modules

### ISSUE THREAD

**Issue by sglavoie** [sglavoie/uol-grades-calculator-server#7]
## Acceptance

* [x] Users should be able to click on a link to show a plot of the progress they have made so far.

## Tasks

* [x] Back-end: Implement POST request to `/plot/modules`.
* [x] Front-end: Implement `PlotModules` component.

## Analysis

For the time being, just output the plot with default options. Customizing options will be handled in a separate issue.
