### ISSUE TITLE
Add Tailwind CSS

### ISSUE THREAD

**Issue by sglavoie** [sglavoie/uol-grades-calculator-server#8]
## Acceptance

* [x] Tailwind CSS is configured and ready to be used.

## Tasks

* [x] Integrate Tailwind with React. https://tailwindcss.com/docs/guides/create-react-app
* [x] Test Tailwind in the App component to make sure it works.
* [x] Add some basic styles for existing components.
  * [x] `CheckScoreAccuracy`
  * [x] `HeaderFull`
  * [x] `HeaderLimited`
  * [x] `HomePage`
  * [x] `NotFound`
  * [x] `PlotModules`
  * [x] `SummarizeAll`
  * [x] `SummarizeDone`
  * [x] `SummarizeProgress`
  * [x] `Uploader`
