### ISSUE TITLE
Back-end: `/plot-modules` should accept options to customize plot outputs

### ISSUE THREAD

**Issue by sglavoie** [sglavoie/uol-grades-calculator-server#9]
## Acceptance

* [x] All the options defined in the task list are supported in the back-end and will return a custom plot.

## Tasks

* [x] Pass options to the CLI in `backend/src/main.py`.
* [x] Test support of the following options from https://github.com/sglavoie/uol-grades-calculator/blob/161345187241982dea9ae5c0d5e817e908a2051f/ugc/commands.py#L81:
  * [x] `dpi`
  * [x] `title`
  * [x] `title_keep_date`
  * [x] `title_no_date`
  * [x] `no_trend`
  * [x] `no_module_names`
  * [x] `no_grades`
  * [x] `no_avgs`
  * [x] `no_avg_weighted`
  * [x] `no_avg_unweighted`
  * [x] `long_module_names`

**Comment by sglavoie** [comment]
FIXED: Options passed in 64481a24326d135e3b17f7f3c614853b57eace4a.
